In [1]:
#this code deals with finding riped tomatoes from tomatoes.jpg

import cv2
import numpy as np

In [2]:
#Read image
img = cv2.imread("tomato.jpg") 



#Convert BGR to HSV
# (HUE---SATURATION--VALUE)


hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

In [3]:
#Color strength parameters in HSV
#Color strength parameters in HSV
#Range of red Color in HSV

weaker = np.array([0,0,100])
stronger = np.array([10,255,255])

In [4]:
#Threshold HSV image to obtain input color
mask = cv2.inRange(hsv, weaker, stronger)
cv2.imshow('mask',mask)
# mask only selects red pigments

#getting the red color back
fg = cv2.bitwise_or(img, img, mask=mask)
cv2.imshow('fg',fg)

#inverted mask.....ie getting non red color in image....turning it to black
mask_i = cv2.bitwise_not(mask)

bg = cv2.bitwise_or(img, img, mask=mask_i)
cv2.imshow('bg',bg)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [38]:
output_img = bg.copy()
output_img[mask == 255] = [180, 150, 255]

In [39]:
cv2.imshow('mask',output_img)
cv2.waitKey(0)
cv2.destroyAllWindows()